insert into AUTHOR (id, name) values ('1', 'Fábio Teixeira');
insert into AUTHOR (id, name) values ('2', 'Jonh Walker');
insert into AUTHOR (id, name) values ('3', 'Bobby Singer');
insert into AUTHOR (id, name) values ('4', 'Samuel Campbell');
insert into POST (id, author_id, content) values ('1', '1', 'Primeiro post da aplicação.');
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_POST;