insert into AUTHOR (id, name) values ('1', 'Fábio Teixeira');
insert into AUTHOR (id, name) values ('2', 'Jonh Walker');
insert into AUTHOR (id, name) values ('3', 'Bobby Singer');
insert into AUTHOR (id, name) values ('4', 'Samuel Campbell');
insert into POST (id, author_id, content, data) values ('1', '1', 'Primeiro post da aplicação.', '2019-01-01');
insert into POST (id, author_id, content, data) values ('2', '4', 'Segundo post da aplicação.', '2018-01-01');
insert into COMMENT (id, post_id, content, data) values ('1', '1', 'Esse é o primeiro comentário', '2019-01-01');
insert into COMMENT (id, post_id, content, data) values ('2', '1', 'Esse é o segundo comentário', '2019-01-01');
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_AUTHOR;
call next value for SE_POST;
call next value for SE_POST;
call next value for SE_COMMENT;
call next value for SE_COMMENT;